zotero:
  user_id: 14436949
  api_key: lTis0w5zmu096RXN5VFoLhVT
  include_path: null

email:
  sender: jiangy19@gmail.com
  receiver: jyp23@mails.tsinghua.edu.cn
  smtp_server: smtp.gmail.com
  smtp_port: 465
  sender_password: abecibarhravjchz

llm:
  api:
    key: sk-ypqeqxqhpzapzcokrqkgomjyxkrfbcztpvyslvjagnryksls
    base_url: https://api.siliconflow.cn/v1
  generation_kwargs:
    model: deepseek-ai/DeepSeek-R1-0528-Qwen3-8B

source:
  arxiv:
    category: ["cs.AI","cs.CV","cs.RO"]

executor:
  debug: ${oc.env:DEBUG,null}
  source: ['arxiv']
